# Site settings
author: Brandon Brasson
title: House of coding 
header-img: img/home-bg.png
email: rocksong622@gmail.com
copyright_name: Brandon Brasson
description: > # this means to ignore newlines until "baseurl:"
  // ruby gem
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  BrandonBrasson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
